### ISSUE TITLE
Missing device: Arturia MicroFreak

### ISSUE THREAD

**Issue by snej** [audionerd/minimidi-data#11]
The manual doesn't state the polarity; it says nothing more than "use the dongle we included."
[This post on Reddit](https://www.reddit.com/r/MicroFreak/comments/flbfvz/is_the_trs_midi_type_a_or_type_b/fq9l0aa/?utm_source=reddit&utm_medium=web2x&context=3) says it's type B, but I haven't confirmed.

**Comment by audionerd** [comment]
Added as Type B for now. Thanks!
