### ISSUE TITLE
TRS-MIDI is not MIDI 2.0

### ISSUE THREAD

**Issue by bome** [audionerd/minimidi-data#14]
Hi,
first of all, thank you very much for this informative and useful web page!

On the actual site https://minimidi.world/ , the TRS-MIDI spec is mentioned three times to be part of the MIDI 2.0 standard. This is not true, TRS-MIDI is a "normal" MIDI standard and (currently) only used for MIDI 1.0 connections.

I think the easiest fix is to replace "MIDI 2.0" with "MIDI" three times from that web page.

Thank you very much!
Florian (Technical Standards Board of the MIDI Association)

PS: if there's a better place to communicate, let me know!

**Comment by audionerd** [comment]
Thanks for the report and clear explanation! Fixed.

**Comment by bome** [comment]
excellent, thanks a lot!
