### ISSUE TITLE
Missing device: Expressive E Touché

### ISSUE THREAD

**Issue by chansexpressiveee** [audionerd/minimidi-data#16]
Hi, it's Chris from Expressive E. Your minimidi.world page is a true treasure - thank you for this. 

If you find the time, feel free to add our Expressive E **Touché** to the list. Our device is working with **Type B**.
It has MIDI IN/OUT TRS jacks. It's a MIDI/CV controller.

Thank you for your consideration!

Chris

**Comment by audionerd** [comment]
hi chris! thanks for the kind words. just added the touché, should show up on the site shortly.

**Comment by chansexpressiveee** [comment]
Awesome, thank you, it's online. :)
