### ISSUE TITLE
Missing Device: Moog Subharmonicon

### ISSUE THREAD

**Issue by turunturun** [audionerd/minimidi-data#21]
Moog Subharmonicon implements Type-A MIDI, from manual pg 36:
MIDI information is received via this jack using the five-pin DIN socket to
3.5mm MINI jack (MIDI Type A) adapter included with your Subharmonicon.
Specifically, Subharmonicon can receive master clock (TEMPO) information,
note data, and various CC (Control Change) messages via MIDI (see MIDI
Operations table on page 44).

**Comment by audionerd** [comment]
Added. Thanks!
