### ISSUE TITLE
Missing device Beatbuddy

### ISSUE THREAD

**Issue by AndersGaden** [audionerd/minimidi-data#27]
Beatbuddy by Singular Sound use a 6 pin connector for midi

**Comment by audionerd** [comment]
Interesting. They use a [PS/2 to 5-pin MIDI IN/OUT breakout cable](https://www.singularsound.com/products/midi-sync-cable). I’m not sure if this belongs in the data, which is focused on TRS MIDI, but maybe it should be called out on the site.
