### ISSUE TITLE
midi.org links broken

### ISSUE THREAD

**Issue by amstan** [audionerd/minimidi-data#29]
Hey, under [Read More](https://minimidi.world/#read-more), you have a couple of [midi.org/articles-old](https://midi.org/articles-old) links but they're both broken:

* https://www.midi.org/articles-old/trs-specification-adopted-and-released
* https://www.midi.org/articles-old/updated-how-to-make-your-own-3-5mm-mini-stereo-trs-to-midi-5-pin-din-cables

Looks like it's just a matter of `s/articles-old/articles/`:

* https://www.midi.org/articles/trs-specification-adopted-and-released
* https://www.midi.org/articles/updated-how-to-make-your-own-3-5mm-mini-stereo-trs-to-midi-5-pin-din-cables

PS: Awesome website!

**Comment by audionerd** [comment]
Thanks!
