### ISSUE TITLE
Missing device: M-Audio Air

### ISSUE THREAD

**Issue by dylhunn** [audionerd/minimidi-data#3]
The [Air](https://m-audio.com/air-192-6) line of audio interfaces appears to be missing. I believe it is type A.

**Comment by dylhunn** [comment]
Excuse me, this is actually the correct link here: https://m-audio.com/air-192-14

Not all of the Air models have TRS Midi jacks, but the 192|14 does.

**Comment by audionerd** [comment]
Thanks. Couldn't find the type documented. Will mark as A for now.
