### ISSUE TITLE
Bidirectional circuits

### ISSUE THREAD

**Issue by amstan** [audionerd/minimidi-data#30]
Hey, I'm toying with the idea to make a new usb midi adapter that has the TRS connectors.

I dislike the A/B split thing, I don't really want to have physical buttons.

At least for the recieve side, this might be solvable with just a bunch of electronics. Do you have any examples of this? A device on your list that has an input that autodetects?

For my idea, refer to the schematics:
![schematics](https://cdn.sparkfun.com/assets/learn_tutorials/4/0/8/midihw.gif)

If I were to double up that opto-isolator, put it in parallel with the previous one. Connect the transistor outputs in the same spots (pin 4 to 4 and 5 to 5), but reverse the inputs (1 to 2 and 2 to 1). At that point D1 is redundant since each optoisolator V_f should make sure it's under the other's V_r.

No idea how one would do bidirectional transmit, current would flow pretty similarly in both directions. I guess I would need some kind of software based switch if i want to keep it neat.

**Comment by amstan** [comment]
Darn, I should have done more reading.

https://www.elektronauts.com/t/elektron-3-5mmtrs-din-midi-adapters/81634/14
> The MIDI IN port is configured automatically

> The MIDI 3.5 mm jack can take either polarity MIDI input cable.

> The input is auto-cross-over and each output has its own switch 

> The MIDI input is 3.5mm stereo TRS, with our own invented auto-crossover

> 3.5mm auto crossover TRS MIDI Input

> “Rev1.1 of the device … features PSImidi which allows ANY type of TRS MIDI cable to be used on the input.”

Googling that found this "PSImidi" circuit, which is slightly different than my idea of using 2 optos, uses a full bridge rectifier instead:

https://modwiggler.com/forum/viewtopic.php?p=3027630#p3027630

> “PSImidi … allows any TRS midi cable to be used.”

> i/o auto-crossover in & user selectable out

Anyway, what I'm saying is that perhaps these types of circuits should be documented on your website in case anyone wants to implement them on a device.

**Comment by audionerd** [comment]
MICROMIDITRS-USB sounds close to what you’re describing and the firmware is on GitHub:
https://github.com/okyeron/MICROMIDITRS-USB
https://denki-oto.weebly.com/store/p74/MICROMIDITRS-USB.html

For circuit ideas you might try a search on the [modwiggler](https://www.modwiggler.com/forum) or [lines](https://llllllll.co) forums.

**Comment by amstan** [comment]
> MICROMIDITRS-USB sounds close to what you’re describing

For sure! That looks pretty good, thanks for the link.

I can't really find the schematic for it though. I see references to a "[LPZW](http://leipzigwest.org/) Auto Crossover circuit".

What do you think about having such a crossover circuit (assuming we can figure out what's good) on your website?

**Comment by audionerd** [comment]
I think for simplicity sake that probably doesn’t belong on the site. But if you found a good solution feel free to update this issue thread. Thanks!
