### ISSUE TITLE
2 missing entries :DIMENSION MK3 by Ziqal and  Droid by Der Mann mit der Maschine

### ISSUE THREAD

**Issue by Thirteenmoons** [audionerd/minimidi-data#36]
Hello, 

The Droid by Der Mann mit der Maschine uses trs Midi  I’m unaware of it is A or B.

https://shop.dermannmitdermaschine.de/

Also

 The  DIMENSION MK3 by Ziqal uses trs midi as well.  Modular grid eludes to it using both A &  B but I could not verify this on their site. 
 
https://ziqal.com/?v=d3dcf429c679

**Comment by audionerd** [comment]
Thanks. The manual for the DROID X7 says it supports MIDI TRS type A and B (auto-sensing input). I’ll take a look at adding it.

**Comment by Thirteenmoons** [comment]
Very happy to help. Your site is an excellent resource and I love it.  Thanks for creating it.  I have linked it to many people and it as helped a great amount.   Thanks for being thoughtful Sent from my iPadOn Jan 12, 2023, at 18:37, Eric Skogen ***@***.***> wrote:﻿
Thanks. The manual for the DROID X7 says it supports MIDI TRS type A and B (auto-sensing input). I’ll take a look at adding it.

**Comment by audionerd** [comment]
According to Perfect Circuit, the Ziqal Dimension MK3 input is MIDI TRS type A. Just added both devices to the site. Thanks for the kind words :)
