### ISSUE TITLE
New product submission - Novation FLkey Mini

### ISSUE THREAD

**Issue by synthfiend** [audionerd/minimidi-data#37]
I am brand new here and don't know how to add another product yet, but here's my first attempt at providing the info you need to do so. 
_:novation-flkey-mini device:make "Novation" .
_:novation-flkey-mini device:model "FLkey Mini" .
_:novation-flkey-mini device:outputs 1 .
_:novation-flkey-mini device:typeA true .
_:novation-flkey-mini device:notes "Brief notes about the device" .
_:novation-flkey-mini device:details "Longer detailed description" .
_:novation-flkey-mini device:uri "https://novationmusic.com/en/keys/flkey" .

**Comment by audionerd** [comment]
Thanks! Added.
