### ISSUE TITLE
Missing devices

### ISSUE THREAD

**Issue by Gsnorgathon** [audionerd/minimidi-data#43]
Make: Poly Effects
Model: Digit (if serial number is less than 474)
MIDI TRS: Type B

Make: Poly Effects
Model: Digit (if serial number is 474 or greater)
MIDI TRS: Type A

Make: Poly Effects
Model: Beebo (if serial number is less than 338)
MIDI TRS: Type B

Make: Poly Effects
Model: Beebo (if serial number is 338 or greater)
MIDI TRS: Type A

**Comment by audionerd** [comment]
Added. Thanks @Gsnorgathon!
