### ISSUE TITLE
Missing device: Polyend Tracker

### ISSUE THREAD

**Issue by mattb** [audionerd/minimidi-data#7]
https://help.polyend.com/639766-Is-the-Polyend-Tracker-MIDI-compatible

"it can send and receive MIDI messages over its dedicated mini-TRS Type B MIDI ports"

**Comment by audionerd** [comment]
Thanks! Added in ab390c6.

**Comment by mattb** [comment]
Awesome! Thanks for maintaining such a useful resource.
